apiVersion: batch/v1
kind: Job
metadata:
  name: mobilenet-trainer-standlone
spec:
  parallelism: 1 
  completions: 1
  template:
    metadata:
      labels:
        paddle-job: mobilenet-standlone
    spec:
      imagePullSecrets:
      - name: tangwei12 
      hostNetwork: true
      serviceAccountName: paddle
      containers:
      - name: trainer
        image: "registry.baidu.com/tangwei12/models:dev"
        imagePullPolicy: Always
        #command: ["python", "/models/image_classification/se_resnext.py", "40"]
        command: ["sleep", "86400"]
        env:
        - name: PADDLE_JOB_NAME
          value: mobilenet-standlone
        - name: TRAINING_ROLE
          value: "TRAINER"
        - name: TRAINERS
          value: "4"
        - name: PSERVERS
          value: "2"
        - name: TOPOLOGY
          value: ""
        - name: ENTRY
          value: "python /models/image_classification/mobilenet.py --local 1"
        - name: TRAINER_PACKAGE
          value: "/models"
        - name: PADDLE_INIT_PORT
          value: "30236"
        - name: PADDLE_INIT_NICS
          value: "xgbe0"
        - name: PADDLE_INIT_TRAINER_COUNT
          value: "1"
        - name: PADDLE_INIT_PORTS_NUM
          value: "1"
        - name: PADDLE_INIT_PORTS_NUM_FOR_SPARSE
          value: "1"
        - name: PADDLE_INIT_NUM_GRADIENT_SERVERS
          value: "20"
        - name: PADDLE_INIT_NUM_PASSES
          value: "1"
        - name: PADDLE_INIT_USE_GPU
          value: "0"
        - name: LD_LIBRARY_PATH
          value: "/usr/local/lib:/usr/local/nvidia/lib64"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: "status.podIP"
        resources:
          requests:
            memory: 40Gi
            cpu: 4
          limits:
            memory: 40Gi
            cpu: 4
      restartPolicy: Never
