apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: mobilenet-pserver
spec:
  replicas: 4 
  template:
    metadata:
      labels:
        paddle-job-pserver: mobilenet
    spec:
      hostNetwork: true
      serviceAccountName: paddle
      imagePullSecrets:
      - name: tangwei12
      containers:
      - name: pserver
        image: "registry.baidu.com/tangwei12/models:dev"
        imagePullPolicy: Always
        ports:
        - name: jobport-30236
          containerPort: 30236
        env:
        - name: GLOG_v 
          value: "2"
        - name: GLOG_logtostderr
          value: "1"
        - name: PADDLE_JOB_NAME
          value: mobilenet
        - name: MKL_NUM_THREADS
          value: "1"
        - name: TRAINING_ROLE
          value: "PSERVER"
        - name: TRAINERS
          value: "4"
        - name: PSERVERS
          value: "4"
        - name: TOPOLOGY
          value: ""
        - name: ENTRY
          value: "python /models/image_classification/mobilenet.py --local 0"
        - name: TRAINER_PACKAGE
          value: "/models"
        - name: PADDLE_INIT_PSERVER_PORT
          value: "30236"
        - name: PADDLE_INIT_TRAINER_PORT
          value: "31236"
        - name: PADDLE_INIT_NICS
          value: "xgbe0"
        - name: PADDLE_INIT_TRAINER_COUNT
          value: "1"
        - name: PADDLE_INIT_PORTS_NUM
          value: "1"
        - name: PADDLE_INIT_PORTS_NUM_FOR_SPARSE
          value: "1"
        - name: PADDLE_INIT_NUM_GRADIENT_SERVERS
          value: "20"
        - name: PADDLE_INIT_NUM_PASSES
          value: "1"
        - name: PADDLE_INIT_USE_GPU
          value: "0"
        - name: LD_LIBRARY_PATH
          value: "/usr/local/lib:/usr/local/nvidia/lib64"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: "status.podIP"
        command: ["paddle_k8s", "start_fluid"]
        #command: ["sleep", "3600"]
        resources:
          requests:
            memory: 40Gi
            cpu: 4
          limits:
            memory: 40Gi
            cpu: 4
